DROP TABLE PRESCRIPTION;
DROP TABLE DOCTOR;
DROP TABLE COMPANYXPATIENT;
DROP TABLE COMPANY;
DROP TABLE PATIENT;

CREATE TABLE DOCTOR 
  ( 
     DOCTOR_ID    NUMBER(5), 
     FNAME VARCHAR2 (15) NOT NULL, 
     LNAME VARCHAR2(15) NOT NULL, 
     PHONE NUMBER(12),
	 BEEPER VARCHAR2 (12),
     PRESC_AMOUNT NUMBER,
	 
	 CONSTRAINT DOCTOR_ID_PK PRIMARY KEY(DOCTOR_ID)
  ); 
  
CREATE TABLE PATIENT 
( 
	 PATIENT_ID NUMBER(5), 
     FNAME     VARCHAR2 (15) NOT NULL, 
     LNAME     VARCHAR2(15) NOT NULL, 
     STREET    VARCHAR2(15) NOT NULL, 
     CITY      VARCHAR2 (10) NOT NULL, 
     STATE     VARCHAR2 (12) NOT NULL, 
     ZIP       VARCHAR2(5) NOT NULL, 
     PHONE     NUMBER(12),

    CONSTRAINT PATIENT_ID_PK PRIMARY KEY(PATIENT_ID)
); 
  
CREATE TABLE COMPANY /*HEALTH_INSURANCE*/
  ( 
	 COMPANY_ID	   NUMBER(5) ,
     NAME       VARCHAR2(15), 
     CONTACT_FNAME VARCHAR2(15), 
     CONTACT_LNAME  VARCHAR2 (15), 
     PHONE         NUMBER (12),
     PRESC_AMOUNT NUMBER,

	 CONSTRAINT COMPANY_ID_PK PRIMARY KEY(COMPANY_ID)
); 
  
  
CREATE TABLE COMPANYXPATIENT 
  ( 
	 ID	NUMBER(5),	
     COMPANY_ID NUMBER(5),
	 PATIENT_ID NUMBER(5), 

	 CONSTRAINT COMPANYXPATIENT_ID_PK PRIMARY KEY(ID),	 
	 CONSTRAINT COMPANYXPATIENT_UNIQUE UNIQUE(COMPANY_ID,PATIENT_ID),
	 CONSTRAINT PATIENT_ID_FK FOREIGN KEY(PATIENT_ID) REFERENCES PATIENT(PATIENT_ID),
	 CONSTRAINT COMPANY_ID_FK FOREIGN KEY(COMPANY_ID) REFERENCES COMPANY(COMPANY_ID)
  ); 
  
CREATE TABLE PRESCRIPTION 
  ( 
     PRESC_ID NUMBER(5),
	 ID   			NUMBER (5), 
	 DOCTOR_ID		NUMBER(5),
     PDATE     		DATE NOT NULL,
     POBS	        VARCHAR2 (50) NOT NULL,
	 
	 CONSTRAINT PRESC_ID_PK PRIMARY KEY(PRESC_ID),	 
	 CONSTRAINT COMPANYXPATIENT_ID_FK  FOREIGN KEY(ID) REFERENCES COMPANYXPATIENT(ID),
	 CONSTRAINT DOCTOR_ID_FK  FOREIGN KEY(DOCTOR_ID) REFERENCES DOCTOR(DOCTOR_ID)
); 

DROP SEQUENCE DOCTOR_DOCTOR_ID_SEQ;
CREATE SEQUENCE DOCTOR_DOCTOR_ID_SEQ;
       
INSERT INTO DOCTOR(DOCTOR_ID,FNAME,LNAME,PHONE,BEEPER,PRESC_AMOUNT)
VALUES      (DOCTOR_DOCTOR_ID_SEQ.NEXTVAL, 
             'ALex', 
             'JACKSON ', 
             6477622262, 
             5551212,
0); 

INSERT INTO DOCTOR(DOCTOR_ID,FNAME,LNAME,PHONE,BEEPER,PRESC_AMOUNT) 
VALUES      (DOCTOR_DOCTOR_ID_SEQ.NEXTVAL, 
             'perry', 
             'cox ', 
             6477622200, 
             5551213,
0); 

INSERT INTO DOCTOR(DOCTOR_ID,FNAME,LNAME,PHONE,BEEPER,PRESC_AMOUNT) 
VALUES      (DOCTOR_DOCTOR_ID_SEQ.NEXTVAL, 
             'Eloit', 
             'Ried ', 
             6477622211, 
             5551214,
0); 

INSERT INTO DOCTOR(DOCTOR_ID,FNAME,LNAME,PHONE,BEEPER,PRESC_AMOUNT)
VALUES      (DOCTOR_DOCTOR_ID_SEQ.NEXTVAL, 
             'Jp', 
             'Dorain ', 
             6477622233, 
             5551215,
0); 

INSERT INTO DOCTOR(DOCTOR_ID,FNAME,LNAME,PHONE,BEEPER,PRESC_AMOUNT) 
VALUES      (DOCTOR_DOCTOR_ID_SEQ.NEXTVAL, 
             'Bob', 
             'Kelso', 
             6477622244, 
             5551216,
0); 
INSERT INTO DOCTOR(DOCTOR_ID,FNAME,LNAME,PHONE,BEEPER,PRESC_AMOUNT) 
VALUES      (DOCTOR_DOCTOR_ID_SEQ.NEXTVAL, 
             'JENI', 
             'AGA', 
             6477633334, 
             5551217,
0); 
INSERT INTO DOCTOR(DOCTOR_ID,FNAME,LNAME,PHONE,BEEPER,PRESC_AMOUNT) 
VALUES      (DOCTOR_DOCTOR_ID_SEQ.NEXTVAL, 
             'ELLISA', 
             'FAHAD', 
             6477633300, 
             5551218,
0); 
INSERT INTO DOCTOR(DOCTOR_ID,FNAME,LNAME,PHONE,BEEPER,PRESC_AMOUNT) 
VALUES      (DOCTOR_DOCTOR_ID_SEQ.NEXTVAL, 
             'ROBERT', 
             'ARDERSON', 
             6477633312, 
             5551219,
0); 
INSERT INTO DOCTOR(DOCTOR_ID,FNAME,LNAME,PHONE,BEEPER,PRESC_AMOUNT) 
VALUES      (DOCTOR_DOCTOR_ID_SEQ.NEXTVAL, 
             'OLIVER', 
             'NELSON', 
             6477633331, 
             5551218,
0); 
INSERT INTO DOCTOR(DOCTOR_ID,FNAME,LNAME,PHONE,BEEPER,PRESC_AMOUNT) 
VALUES      (DOCTOR_DOCTOR_ID_SEQ.NEXTVAL, 
             'IDRIS', 
             'HAGOS', 
             6477633339, 
             5551219,
0); 
INSERT INTO DOCTOR(DOCTOR_ID,FNAME,LNAME,PHONE,BEEPER,PRESC_AMOUNT) 
VALUES      (DOCTOR_DOCTOR_ID_SEQ.NEXTVAL, 
             'Bella', 
             'Khan', 
             647763323, 
             5551220,
0);
INSERT INTO DOCTOR(DOCTOR_ID,FNAME,LNAME,PHONE,BEEPER,PRESC_AMOUNT) 
VALUES      (DOCTOR_DOCTOR_ID_SEQ.NEXTVAL, 
             'Alisandra', 
             'Khosie', 
             647764000, 
             5551221,
0);
INSERT INTO DOCTOR(DOCTOR_ID,FNAME,LNAME,PHONE,BEEPER,PRESC_AMOUNT) 
VALUES      (DOCTOR_DOCTOR_ID_SEQ.NEXTVAL, 
             'Shana', 
             'Khiar', 
             647564088, 
             5551222,
0);

CREATE INDEX PATIENT_LAST_NAME_I
ON PATIENT(LNAME);
DROP SEQUENCE PATIENT_PATIENT_ID_SEQ;
CREATE SEQUENCE PATIENT_PATIENT_ID_SEQ;
       
INSERT INTO PATIENT(PATIENT_ID,FNAME,LNAME,STREET,CITY,STATE,ZIP,PHONE)
VALUES     (PATIENT_PATIENT_ID_SEQ.NEXTVAL, 
            'Jim', 
            'Perotti', 
            '12 Oak St', 
            'Shade', 
            'OH', 
            45701, 
            7863333); 

INSERT INTO PATIENT(PATIENT_ID,FNAME,LNAME,STREET,CITY,STATE,ZIP,PHONE) 
VALUES     (PATIENT_PATIENT_ID_SEQ.NEXTVAL, 
            'Glien', 
            'Stamier', 
            '1 Walnut Ave', 
            'Athens', 
            'FL', 
            45702, 
            7863333); 

INSERT INTO PATIENT(PATIENT_ID,FNAME,LNAME,STREET,CITY,STATE,ZIP,PHONE) 
VALUES     (PATIENT_PATIENT_ID_SEQ.NEXTVAL, 
            'Maddy', 
            'Gary', 
            '45 marple St', 
            'Toronto', 
            'ON', 
            45703, 
            686333344); 

INSERT INTO PATIENT(PATIENT_ID,FNAME,LNAME,STREET,CITY,STATE,ZIP,PHONE) 
VALUES     (PATIENT_PATIENT_ID_SEQ.NEXTVAL, 
            'Black', 
            'Shelton', 
            '3 Ekn Olv', 
            'Shade', 
            'OH', 
            45704, 
            5863333); 

INSERT INTO PATIENT(PATIENT_ID,FNAME,LNAME,STREET,CITY,STATE,ZIP,PHONE) 
VALUES     (PATIENT_PATIENT_ID_SEQ.NEXTVAL, 
            'EJ', 
            'Thomson', 
            '92 Ash St', 
            'Orlando', 
            'FL', 
            85705, 
            5863332); 

INSERT INTO PATIENT(PATIENT_ID,FNAME,LNAME,STREET,CITY,STATE,ZIP,PHONE) 
VALUES     (PATIENT_PATIENT_ID_SEQ.NEXTVAL, 
            'Dyrk', 
            'Ashton', 
            '33 Poptar Ave', 
            'Columbus', 
            'OH', 
            45706, 
            6863332); 
INSERT INTO PATIENT(PATIENT_ID,FNAME,LNAME,STREET,CITY,STATE,ZIP,PHONE) 
VALUES     (PATIENT_PATIENT_ID_SEQ.NEXTVAL, 
            'Neema', 
            'Saeed', 
            'Steeles Ave', 
            'Markham', 
            'ON', 
            45707, 
            6863330); 

INSERT INTO PATIENT(PATIENT_ID,FNAME,LNAME,STREET,CITY,STATE,ZIP,PHONE) 
VALUES     (PATIENT_PATIENT_ID_SEQ.NEXTVAL, 
            'Neema', 
            'Saeed', 
            'Steeles Ave', 
            'Markham', 
            'ON', 
            45707, 
            6863330); 
INSERT INTO PATIENT(PATIENT_ID,FNAME,LNAME,STREET,CITY,STATE,ZIP,PHONE) 
VALUES     (PATIENT_PATIENT_ID_SEQ.NEXTVAL, 
            'Sofia', 
            'Shah', 
            'Cosburn', 
            'Toronto', 
            'ON', 
            45708, 
            6863344); 
            
INSERT INTO PATIENT(PATIENT_ID,FNAME,LNAME,STREET,CITY,STATE,ZIP,PHONE) 
VALUES     (PATIENT_PATIENT_ID_SEQ.NEXTVAL, 
            'Eman', 
            'Mohamed', 
            'Clock Tower Ave', 
            'Ajax', 
            'ON', 
            45709, 
            6863319); 
                                    
INSERT INTO PATIENT(PATIENT_ID,FNAME,LNAME,STREET,CITY,STATE,ZIP,PHONE) 
VALUES     (PATIENT_PATIENT_ID_SEQ.NEXTVAL, 
            'Amany', 
            'Abdulmohsen', 
            'Leside Ave', 
            'London', 
            'ON', 
            45710, 
            6863382); 
                                   
                    
CREATE INDEX COMPANY_NAME_I
ON COMPANY(NAME);         
DROP SEQUENCE COMPANY_COMPANY_ID_SEQ;
CREATE SEQUENCE COMPANY_COMPANY_ID_SEQ;    

INSERT INTO COMPANY(COMPANY_ID,NAME,CONTACT_FNAME,CONTACT_LNAME,PHONE,PRESC_AMOUNT) 
VALUES      (COMPANY_COMPANY_ID_SEQ.NEXTVAL,'Prundetial', 
             'Jan', 
             'Johnson', 
             5554567,
0); 

INSERT INTO COMPANY(COMPANY_ID,NAME,CONTACT_FNAME,CONTACT_LNAME,PHONE,PRESC_AMOUNT)  
VALUES      (COMPANY_COMPANY_ID_SEQ.NEXTVAL,'State Farm', 
             'Sam', 
             'Smith', 
             5558765,
0); 

INSERT INTO COMPANY(COMPANY_ID,NAME,CONTACT_FNAME,CONTACT_LNAME,PHONE,PRESC_AMOUNT)  
VALUES      (COMPANY_COMPANY_ID_SEQ.NEXTVAL,'Nationwide', 
             'Fandy', 
             'Buck', 
             5559854,
0); 
INSERT INTO COMPANY(COMPANY_ID,NAME,CONTACT_FNAME,CONTACT_LNAME,PHONE,PRESC_AMOUNT)  
VALUES      (COMPANY_COMPANY_ID_SEQ.NEXTVAL,'Sunshine', 
             'Eduardo', 
             'Jozeph', 
             5558711,
0); 
INSERT INTO COMPANY(COMPANY_ID,NAME,CONTACT_FNAME,CONTACT_LNAME,PHONE,PRESC_AMOUNT)  
VALUES      (COMPANY_COMPANY_ID_SEQ.NEXTVAL,'Sunshine', 
             'ALEXANDRA', 
             'DAOOD', 
             5558720,
0); 
INSERT INTO COMPANY(COMPANY_ID,NAME,CONTACT_FNAME,CONTACT_LNAME,PHONE,PRESC_AMOUNT)  
VALUES      (COMPANY_COMPANY_ID_SEQ.NEXTVAL,'Sunset', 
             'Ahmed', 
             'Seraj', 
             5558350,
0); 
INSERT INTO COMPANY(COMPANY_ID,NAME,CONTACT_FNAME,CONTACT_LNAME,PHONE,PRESC_AMOUNT)  
VALUES      (COMPANY_COMPANY_ID_SEQ.NEXTVAL,'Medgulf', 
             'Julia', 
             'Mathio', 
             5558512,
0);
INSERT INTO COMPANY(COMPANY_ID,NAME,CONTACT_FNAME,CONTACT_LNAME,PHONE,PRESC_AMOUNT)  
VALUES      (COMPANY_COMPANY_ID_SEQ.NEXTVAL,'Bupa', 
             'Maria', 
             'Sultan', 
             5558507,
0);
INSERT INTO COMPANY(COMPANY_ID,NAME,CONTACT_FNAME,CONTACT_LNAME,PHONE,PRESC_AMOUNT)  
VALUES      (COMPANY_COMPANY_ID_SEQ.NEXTVAL,'Admas', 
             'Joana', 
             'Adam', 
             5558000,
0);
INSERT INTO COMPANY(COMPANY_ID,NAME,CONTACT_FNAME,CONTACT_LNAME,PHONE,PRESC_AMOUNT)  
VALUES      (COMPANY_COMPANY_ID_SEQ.NEXTVAL,'Manaly', 
             'Meme', 
             'Poland', 
             5558099,
0);
INSERT INTO COMPANY(COMPANY_ID,NAME,CONTACT_FNAME,CONTACT_LNAME,PHONE,PRESC_AMOUNT)  
VALUES      (COMPANY_COMPANY_ID_SEQ.NEXTVAL,'Ayman', 
             'Amalia', 
             'Oglo', 
             5558034,
0);
DROP SEQUENCE COMPANYXPATIENT_ID_SEQ;
CREATE SEQUENCE COMPANYXPATIENT_ID_SEQ;

INSERT INTO COMPANYXPATIENT(ID,COMPANY_ID,PATIENT_ID) 
VALUES      (COMPANYXPATIENT_ID_SEQ.NEXTVAL,1,1); 

INSERT INTO COMPANYXPATIENT(ID,COMPANY_ID,PATIENT_ID)  
VALUES      (COMPANYXPATIENT_ID_SEQ.NEXTVAL,1,2);

INSERT INTO COMPANYXPATIENT(ID,COMPANY_ID,PATIENT_ID)  
VALUES      (COMPANYXPATIENT_ID_SEQ.NEXTVAL,2,3); 

INSERT INTO COMPANYXPATIENT(ID,COMPANY_ID,PATIENT_ID)  
VALUES      (COMPANYXPATIENT_ID_SEQ.NEXTVAL,2,4);


INSERT INTO COMPANYXPATIENT(ID,COMPANY_ID,PATIENT_ID)  
VALUES      (COMPANYXPATIENT_ID_SEQ.NEXTVAL,3,5); 

INSERT INTO COMPANYXPATIENT(ID,COMPANY_ID,PATIENT_ID)  
VALUES      (COMPANYXPATIENT_ID_SEQ.NEXTVAL,3,6);

INSERT INTO COMPANYXPATIENT(ID,COMPANY_ID,PATIENT_ID)  
VALUES      (COMPANYXPATIENT_ID_SEQ.NEXTVAL,3,3); 

INSERT INTO COMPANYXPATIENT(ID,COMPANY_ID,PATIENT_ID)  
VALUES      (COMPANYXPATIENT_ID_SEQ.NEXTVAL,3,4); 

INSERT INTO COMPANYXPATIENT(ID,COMPANY_ID,PATIENT_ID)  
VALUES      (COMPANYXPATIENT_ID_SEQ.NEXTVAL,2,1); 

INSERT INTO COMPANYXPATIENT(ID,COMPANY_ID,PATIENT_ID)  
VALUES      (COMPANYXPATIENT_ID_SEQ.NEXTVAL,3,1);

INSERT INTO COMPANYXPATIENT(ID,COMPANY_ID,PATIENT_ID)  
VALUES      (COMPANYXPATIENT_ID_SEQ.NEXTVAL,3,2); 

DROP SEQUENCE PRESCRIPTION_PRESC_ID_SEQ;
CREATE SEQUENCE PRESCRIPTION_PRESC_ID_SEQ;

INSERT INTO PRESCRIPTION(PRESC_ID,ID,DOCTOR_ID,PDATE,POBS) 
VALUES      (PRESCRIPTION_PRESC_ID_SEQ.NEXTVAL, 1,1,
            TO_DATE('19-04-13', 'YY-MM-DD'),'Acetaminophen'); 
            
INSERT INTO PRESCRIPTION(PRESC_ID,ID,DOCTOR_ID,PDATE,POBS)  
VALUES      (PRESCRIPTION_PRESC_ID_SEQ.NEXTVAL, 2,2,
            TO_DATE('19-06-13', 'YY-MM-DD'),'Adderall');

INSERT INTO PRESCRIPTION(PRESC_ID,ID,DOCTOR_ID,PDATE,POBS)  
VALUES      (PRESCRIPTION_PRESC_ID_SEQ.NEXTVAL, 3,3,
            TO_DATE('19-03-10', 'YY-MM-DD'),'Alprazolam');

INSERT INTO PRESCRIPTION(PRESC_ID,ID,DOCTOR_ID,PDATE,POBS)  
VALUES      (PRESCRIPTION_PRESC_ID_SEQ.NEXTVAL, 3,3,
            TO_DATE('19-02-23', 'YY-MM-DD'),'Amitriptyline');

INSERT INTO PRESCRIPTION(PRESC_ID,ID,DOCTOR_ID,PDATE,POBS)  
VALUES      (PRESCRIPTION_PRESC_ID_SEQ.NEXTVAL, 4,4,
            TO_DATE('19-02-23', 'YY-MM-DD'),'Amlodipine');

INSERT INTO PRESCRIPTION(PRESC_ID,ID,DOCTOR_ID,PDATE,POBS)  
VALUES      (PRESCRIPTION_PRESC_ID_SEQ.NEXTVAL, 5,4,
            TO_DATE('19-02-20', 'YY-MM-DD'),'Amlodipine');

INSERT INTO PRESCRIPTION(PRESC_ID,ID,DOCTOR_ID,PDATE,POBS)  
VALUES      (PRESCRIPTION_PRESC_ID_SEQ.NEXTVAL, 7,8,
            TO_DATE('19-02-25', 'YY-MM-DD'),'FEFADOL');
            
INSERT INTO PRESCRIPTION(PRESC_ID,ID,DOCTOR_ID,PDATE,POBS)  
VALUES      (PRESCRIPTION_PRESC_ID_SEQ.NEXTVAL, 6,5,
            TO_DATE('19-02-27', 'YY-MM-DD'),'FEFADOL');
            
INSERT INTO PRESCRIPTION(PRESC_ID,ID,DOCTOR_ID,PDATE,POBS)  
VALUES      (PRESCRIPTION_PRESC_ID_SEQ.NEXTVAL, 6,6,
            TO_DATE('19-02-28', 'YY-MM-DD'),'Panadol');
            
INSERT INTO PRESCRIPTION(PRESC_ID,ID,DOCTOR_ID,PDATE,POBS)  
VALUES      (PRESCRIPTION_PRESC_ID_SEQ.NEXTVAL, 7,5,
            TO_DATE('19-04-3', 'YY-MM-DD'),'FEFADOL');
            
INSERT INTO PRESCRIPTION(PRESC_ID,ID,DOCTOR_ID,PDATE,POBS)  
VALUES      (PRESCRIPTION_PRESC_ID_SEQ.NEXTVAL, 6,5,
            TO_DATE('19-06-5', 'YY-MM-DD'),'TORADOL ');
            
COMMIT;

